export NavBar from './NavBar'
export PageTop from './PageTop'
export PageMain from './PageMain'
export ConsumptionForm from './ConsumptionForm'
//export DataTable from './DataTable'
export PageFooter from './PageFooter'
export DatePicker from './DatePicker/DatePicker.vue'
//export DatePicker2 from './datepicker/DatePicker2.vue'
